<?
$PERM["tools"]["2"]="D";
$PERM["tools"]["3"]="D";
$PERM["tools"]["4"]="D";
$PERM["tools"]["13"]="D";
$PERM["tools"]["8"]="D";
$PERM["tools"]["5"]="R";
$PERM["tools"]["7"]="D";
$PERM["tools"]["6"]="R";
$PERM["tools"]["*"]="D";
$PERM["factories"]["*"]="D";
$PERM["catalog"]["6"]="W";
$PERM["upload"]["7"]="T_8";
$PERM["admintools"]["*"]="D";
$PERM["calculator"]["*"]="D";
$PERM["desktop_app"]["*"]="R";
$PERM["personal"]["6"]="W";
$PERM["news"]["6"]="W";
$PERM["about"]["6"]="W";
$PERM["index.php"]["6"]="W";
$PERM["/"]["*"]="R";
?>