insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (68, 'de', 'Lachen') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (69, 'de', 'Grinsen') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (70, 'de', 'Traurig') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (71, 'de', 'Überrascht') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (72, 'de', 'Cool') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (73, 'de', 'Kuss') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (74, 'de', 'Verlegen') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (75, 'de', 'Weinen') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (76, 'de', 'Böse') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (77, 'de', 'Zwinkern') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (78, 'de', 'Ausrufezeichen') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (79, 'de', 'Frage') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (80, 'de', 'Idee') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (81, 'de', 'Sprachlos');
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (82, 'de', 'Skeptisch');
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (83, 'de', 'Mitteilung') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (84, 'de', 'Anweisung') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (85, 'de', 'Idee') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (86, 'de', 'Achtung') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (87, 'de', 'Frage') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (88, 'de', 'Schlecht') ;
insert  into b_forum_smile_lang (SMILE_ID,LID,NAME) values (89, 'de', 'Klasse!') ;